---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1

suites:
  # Nagios Server
  - name: Nagios
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[nagios-cookbook::default]
    attributes:
    driver:
        network:
            - ["private_network", {ip: "192.168.50.200"}]
        customize: 
            memory: 4048 
            cpuexecutioncap: 50

  # Redis Server   
  - name: Redis
    run_list:
      - recipe[nagios-cookbook::redis]
    attributes:
    driver:
        network:
             - ["private_network", {ip: "192.168.50.201"}]

  # Nginx Server
  - name: Nginx
    run_list:
      - recipe[nagios-cookbook::nginx]
    attributes:
    driver:
        network:
             - ["private_network", {ip: "192.168.50.202"}]





