---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1

suites:
  - name: default
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[nagios-cookbook::default]
    attributes:
    driver:
        network:
            - ["private_network", {ip: "192.168.50.200"}]
        customize: 
            memory: 4048 
            cpuexecutioncap: 50



